import { NextResponse } from 'next/server';
import { supabase, SCHEMA } from '@/lib/supabase';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { store_name, articles, notes } = body;

    // Validation
    if (!store_name) {
      return NextResponse.json(
        { success: false, error: 'Store name is required' },
        { status: 400 }
      );
    }

    if (!articles || !Array.isArray(articles) || articles.length === 0) {
      return NextResponse.json(
        { success: false, error: 'At least one article is required' },
        { status: 400 }
      );
    }

    // Validate stock availability for each article
    const validationErrors = [];
    for (const article of articles) {
      if (article.boxes > article.warehouse_stock?.total_available) {
        validationErrors.push(
          `Only ${article.warehouse_stock?.total_available} boxes available for ${article.code}. Please reduce quantity.`
        );
      }
    }

    if (validationErrors.length > 0) {
      return NextResponse.json(
        { success: false, error: validationErrors.join('\n') },
        { status: 400 }
      );
    }

    // Insert each article as a separate row in ro_process
    // RO ID will be auto-generated by the database trigger
    const insertData = articles.map((article: any) => ({
      article_code: article.code,
      boxes_requested: article.boxes,
      boxes_allocated_ddd: 0,
      boxes_allocated_ljbb: 0,
      status: 'QUEUE',
      store_name: store_name,
    }));

    const { data, error } = await supabase
      .from('ro_process')
      .insert(insertData)
      .select('ro_id, article_code, boxes_requested');

    if (error) {
      console.error('Error inserting RO:', error);
      return NextResponse.json(
        { success: false, error: error.message },
        { status: 500 }
      );
    }

    // Get the generated RO ID (all rows will have the same ro_id)
    const roId = data?.[0]?.ro_id;

    return NextResponse.json({
      success: true,
      data: {
        ro_id: roId,
        store_name,
        articles_count: articles.length,
        total_boxes: articles.reduce((sum: number, a: any) => sum + a.boxes, 0),
        status: 'QUEUE',
      },
    });
  } catch (error: any) {
    console.error('Error in submit RO API:', error);
    return NextResponse.json(
      { success: false, error: error.message },
      { status: 500 }
    );
  }
}
